### PR TITLE
Don't mark images executable

### PR DESCRIPTION
**Pull request by ginggs**

### CODE REVIEW

**Comment by davidgfnet** [comment]
Is there any way to tell install: this is an exe, this is a regular file without having to hardcode 644?
Thanks!

**Comment by ginggs** [comment]
Normally the permissions of the file being installed are inherited, but in this case you are creating new copies of the files and the default is for them to be executable.  I think the only way is to override the mode.

**Comment by davidgfnet** [comment]
So then we can just make the images in the repo non-executable right?

**Comment by ginggs** [comment]
I don't think the originals are executable.  At least on my system they aren't, but the copies made with new filenames made by install are.

**Comment by davidgfnet** [comment]
Fair enough

**Pull request merged**
