### PR TITLE
Don't overwrite flags set by the build system

### PR DESCRIPTION
**Pull request by ginggs**

### CODE REVIEW

**Comment by davidgfnet** [comment]
Shouldn't them be "+=" for all vars?

**Comment by ginggs** [comment]
No, we don't want to overwrite architecture and optimizing flags from the build system, so we only assign them if they aren't already assigned and then append the other flags we need.

**Comment by davidgfnet** [comment]
Uhmmm I see. Makes a lot of sense. Where are these guidelines coming from? It would be nice to know them for future projects or so.
Thanks!

**Comment by ginggs** [comment]
I struggled to find a single document that explains all of this thoroughly, but this may be a good starting point:

https://wiki.debian.org/HardeningWalkthrough#Handling_dpkg-buildflags_in_your_upstream_build_system

To fully support all hardened build flags in your upstream buildsystem, please ensure that the following flags are supported:
    CFLAGS, CPPFLAGS and LDFLAGS for code written in C
    CXXFLAGS, CPPFLAGS and LDFLAGS for code written in C++

**Pull request merged**
